### PR TITLE
Create mytopic

### PR DESCRIPTION
**Pull request by dsinghrana**
Hi Team,

@singhdi What is your opinion.

Please could you provide your comments on the topic for creating code generation tool.

### CODE REVIEW

**Comment by singhdi** [comment]
I also feel that it is a good Utility to work upon.

**Comment by dsinghrana** [comment]
Oh, I am glad to hear that.

**Comment by singhdi** [comment]
Along with it i was thinking to created a wiki page for the same.

**Comment by dsinghrana** [comment]
I think the same.

**Pull request merged**
